version: 1
tag_space: 64M
extend_limits: true
scenarios:
  - keymind/the_flood/levels/multiplayer/firefight_aqueduct/faqu_dev
commands:
  release:
    - mercury build --release --output package/game-maps/